// 公共
export const UPDATE_DOCUMENT_CLIENT_HEIGHT = 'UPDATE_DOCUMENT_CLIENT_HEIGHT'
export const UPDATE_DOCUMENT_CLIENT_WIDTH = 'UPDATE_DOCUMENT_CLIENT_WIDTH'
 


// 用户
export const UPDATE_USER_ID = 'UPDATE_USER_ID'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_USER_LAST_LOGIN_TIME = 'UPDATE_USER_LAST_LOGIN_TIME'
